// Using react-icons instead of SVG imports to avoid configuration issues
import { 
  FiPlus as PlusIcon,
  FiX as CloseIcon,
  FiPackage as BoxIcon,
  FiCheckCircle as CheckCircleIcon,
  FiAlertTriangle as AlertIcon,
  FiInfo as InfoIcon,
  FiAlertCircle as ErrorIcon,
  FiZap as BoltIcon,
  FiArrowUp as ArrowUpIcon,
  FiArrowDown as ArrowDownIcon,
  FiFolder as FolderIcon,
  FiVideo as VideoIcon,
  FiMusic as AudioIcon,
  FiGrid as GridIcon,
  FiFile as FileIcon,
  FiDownload as DownloadIcon,
  FiArrowRight as ArrowRightIcon,
  FiUsers as GroupIcon,
  FiPackage as BoxIconLine,
  FiStar as ShootingStarIcon,
  FiDollarSign as DollarLineIcon,
  FiTrash2 as TrashBinIcon,
  FiChevronUp as AngleUpIcon,
  FiChevronDown as AngleDownIcon,
  FiChevronLeft as AngleLeftIcon,
  FiChevronRight as AngleRightIcon,
  FiEdit as PencilIcon,
  FiCheck as CheckLineIcon,
  FiX as CloseLineIcon,
  FiChevronDown as ChevronDownIcon,
  FiChevronUp as ChevronUpIcon,
  FiSend as PaperPlaneIcon,
  FiLock as LockIcon,
  FiMail as EnvelopeIcon,
  FiUser as UserIcon,
  FiCalendar as CalenderIcon,
  FiEye as EyeIcon,
  FiEyeOff as EyeCloseIcon,
  FiClock as TimeIcon,
  FiCopy as CopyIcon,
  FiChevronLeft as ChevronLeftIcon,
  FiUser as UserCircleIcon,
  FiCheckSquare as TaskIcon,
  FiList as ListIcon,
  FiDatabase as TableIcon,
  FiFileText as PageIcon,
  FiPieChart as PieChartIcon,
  FiBox as BoxCubeIcon,
  FiSettings as PlugInIcon,
  FiFileText as DocsIcon,
  FiMail as MailIcon,
  FiMoreHorizontal as HorizontaLDots,
  FiMessageCircle as ChatIcon,
  FiMoreVertical as MoreDotIcon,
  FiAlertTriangle as AlertHexaIcon,
  FiAlertCircle as ErrorHexaIcon
} from 'react-icons/fi';

export {
  ErrorHexaIcon,
  AlertHexaIcon,
  MoreDotIcon,
  DownloadIcon,
  FileIcon,
  GridIcon,
  AudioIcon,
  VideoIcon,
  BoltIcon,
  PlusIcon,
  BoxIcon,
  CloseIcon,
  CheckCircleIcon,
  AlertIcon,
  InfoIcon,
  ErrorIcon,
  ArrowUpIcon,
  FolderIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  GroupIcon,
  BoxIconLine,
  ShootingStarIcon,
  DollarLineIcon,
  TrashBinIcon,
  AngleUpIcon,
  AngleDownIcon,
  PencilIcon,
  CheckLineIcon,
  CloseLineIcon,
  ChevronDownIcon,
  PaperPlaneIcon,
  EnvelopeIcon,
  LockIcon,
  UserIcon,
  CalenderIcon,
  EyeIcon,
  EyeCloseIcon,
  TimeIcon,
  CopyIcon,
  ChevronLeftIcon,
  UserCircleIcon,
  TaskIcon,
  ListIcon,
  TableIcon,
  PageIcon,
  PieChartIcon,
  BoxCubeIcon,
  PlugInIcon,
  DocsIcon,
  MailIcon,
  HorizontaLDots,
  ChevronUpIcon,
  ChatIcon,
  AngleLeftIcon,
  AngleRightIcon,
};
